import type { Metadata } from "next";
import { Geist, Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/ui/toast";
import { TanstackQueryProvider } from "@/utils/tanstack-query";

const _inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});
const _playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair-display",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ethnic Elegance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${_inter.className} ${_playfairDisplay.variable} antialiased bg-secondary`}
      >
        <TanstackQueryProvider>
          {children}
          <ToastProvider />
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
